CREATE TABLE SSC_ETABLISSEMENT
(
  ETABLISSEMENT          VARCHAR2(400 BYTE),
  ID_ADRESSE             NUMBER(22),
  ID_ETABLISSEMENT       NUMBER(22),
  SOFTDELETE             NUMBER(22)             DEFAULT 0,
  ID_ETABLISSEMENT_TYPE  INTEGER,
  ACTIVE                 NUMBER(1)              DEFAULT 1
)